apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: deployment-example
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: hello
  spec:
    containers:
      - name: hello
        image: manabusakai/k8s-hello-world:0.0.2
          ports:
            - containerPort: 8080
            readinessProbe:
              httpGet:
                path: /
                port: 8080
      - name: fluentd
        image: fluent/fluentd:v0.12
          ports:
            - containerPort: 24224
