apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ruby
  template:
      labels:
        app: ruby
    spec:
      containers:
        - name: ruby
          image: manabusakai/k8s-hello-world:0.0.2
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
        - name: fluentd
          image: fluent/fluentd:v0.12
          ports:
            - containerPort: 24224
