apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: k8s-hello-world
  labels:
    app: ruby
spec:
  replicas: 10
  selector:
    matchLabels:
      app: ruby
  template:
    metadata:
      name: k8s-hello-world
      labels:
        app: ruby
    spec:
      containers:
        - name: k8s-hello-world
          image: manabusakai/k8s-hello-world:0.0.1
          ports:
            - containerPort: 8080
